<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Invoices" time="10" tests="2" failures="0" errors="1">
   <testsuite name="Invoices" tests="2" failures="0" errors="1" time="10" timestamp="2019-06-13 14:42:26" hostname="nivedita - 192.168.0.12" id="Test Suites/Lemoney/Invoices">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="/Users/nivedita/git/KatalonFirstUIProject/Reports/Lemoney/Invoices/20190613_144153"/>
         <property name="logFiles" value="/Users/nivedita/git/KatalonFirstUIProject/Reports/Lemoney/Invoices/20190613_144153/execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="nivedita - 192.168.0.12"/>
         <property name="os" value="Mac OS X 64bit"/>
         <property name="katalonVersion" value="5.10.1.1"/>
         <property name="browser" value="Chrome 74.0.3729.169"/>
         <property name="hostAddress" value="192.168.0.12"/>
         <property name="sessionId" value="c59d1d2031727312d93d6c383c81a4b5"/>
         <property name="seleniumVersion" value="3.7.1"/>
         <property name="proxyInformation" value="ProxyInformation{proxyOption=NO_PROXY, proxyServerType=HTTP, password=, proxyServerAddress=, proxyServerPort=0}"/>
         <property name="platform" value="Mac OS X"/>
      </properties>
      <testcase name="Test Cases/Lemoney/Setup and TearDown/Setup" classname="Test Cases/Lemoney/Setup and TearDown/Setup" status="PASSED">
         <system-out><![CDATA[2019-06-13 14:42:27 - [TEST_CASE][PASSED] - Test Cases/Lemoney/Setup and TearDown/Setup: Test Cases/Lemoney/Setup and TearDown/Setup

2019-06-13 14:42:27 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: null

2019-06-13 14:42:27 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseId()): null

2019-06-13 14:42:27 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseVariables()): null

2019-06-13 14:42:27 - [TEST_STEP][PASSED] - println(" This is before test"): null

2019-06-13 14:42:27 - [TEST_STEP][PASSED] - Start setup action : setUp: Method 'setUp' complete successfully

2019-06-13 14:42:27 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2019-06-13 14:42:28 - [MESSAGE][INFO] - Starting 'Chrome' driver

2019-06-13 14:42:28 - [MESSAGE][INFO] - Action delay is set to 0 seconds

2019-06-13 14:42:31 - [MESSAGE][PASSED] - Browser is opened with url: ''

2019-06-13 14:42:31 - [TEST_STEP][PASSED] - navigateToUrl("https://lmpro.netlify.com/"): Navigate to 'https://lmpro.netlify.com/' successfully

2019-06-13 14:42:33 - [MESSAGE][PASSED] - Navigate to 'https://lmpro.netlify.com/' successfully

2019-06-13 14:42:33 - [TEST_STEP][PASSED] - verifyElementPresent(findTestObject("Lemoney/Setup/Login/img_Lemoney_logo"), 10): Object 'Object Repository/Lemoney/Setup/Login/img_Lemoney_logo' is present

2019-06-13 14:42:33 - [MESSAGE][PASSED] - Object 'Object Repository/Lemoney/Setup/Login/img_Lemoney_logo' is present

2019-06-13 14:42:33 - [TEST_STEP][PASSED] - verifyElementPresent(findTestObject("Lemoney/Setup/Login/Title_Lemoney"), 10): Object 'Object Repository/Lemoney/Setup/Login/Title_Lemoney' is present

2019-06-13 14:42:33 - [MESSAGE][PASSED] - Object 'Object Repository/Lemoney/Setup/Login/Title_Lemoney' is present

2019-06-13 14:42:33 - [TEST_STEP][PASSED] - verifyElementPresent(findTestObject("Lemoney/Setup/Login/Title_Making Banking Useful"), 10): Object 'Object Repository/Lemoney/Setup/Login/Title_Making Banking Useful' is present

2019-06-13 14:42:33 - [MESSAGE][PASSED] - Object 'Object Repository/Lemoney/Setup/Login/Title_Making Banking Useful' is present

2019-06-13 14:42:33 - [TEST_STEP][PASSED] - verifyElementPresent(findTestObject("Lemoney/Setup/Login/div_Enter Username  Password"), 10): Object 'Object Repository/Lemoney/Setup/Login/div_Enter Username  Password' is present

2019-06-13 14:42:33 - [MESSAGE][PASSED] - Object 'Object Repository/Lemoney/Setup/Login/div_Enter Username  Password' is present

2019-06-13 14:42:33 - [TEST_STEP][PASSED] - setText(findTestObject("Lemoney/Setup/Login/input_EnterUserName"), "owner@lemoney.com"): Text 'owner@lemoney.com' is set on object 'Object Repository/Lemoney/Setup/Login/input_EnterUserName'

2019-06-13 14:42:34 - [MESSAGE][PASSED] - Text 'owner@lemoney.com' is set on object 'Object Repository/Lemoney/Setup/Login/input_EnterUserName'

2019-06-13 14:42:34 - [TEST_STEP][PASSED] - setText(findTestObject("Lemoney/Setup/Login/input_EnterPassword"), "123456"): Text '123456' is set on object 'Object Repository/Lemoney/Setup/Login/input_EnterPassword'

2019-06-13 14:42:34 - [MESSAGE][PASSED] - Text '123456' is set on object 'Object Repository/Lemoney/Setup/Login/input_EnterPassword'

2019-06-13 14:42:34 - [TEST_STEP][PASSED] - click(findTestObject("Lemoney/Setup/Login/button_Login")): Object: 'Object Repository/Lemoney/Setup/Login/button_Login' is clicked on

2019-06-13 14:42:34 - [MESSAGE][PASSED] - Object: 'Object Repository/Lemoney/Setup/Login/button_Login' is clicked on

2019-06-13 14:42:34 - [MESSAGE][PASSED] - Method 'setUp' complete successfully

2019-06-13 14:42:34 - [TEST_STEP][PASSED] - waitForElementPresent(findTestObject("Lemoney/Setup/Logout/img_profileImage"), 10): Object 'Object Repository/Lemoney/Setup/Logout/img_profileImage' is present

2019-06-13 14:42:35 - [MESSAGE][PASSED] - Object 'Object Repository/Lemoney/Setup/Logout/img_profileImage' is present

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseId()): null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseStatus()): null]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <testcase name="Test Cases/Lemoney/DataBase/DatabaseConnection" classname="Test Cases/Lemoney/DataBase/DatabaseConnection" status="ERROR">
         <error type="ERROR" message="Test Cases/Lemoney/DataBase/DatabaseConnection FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation &quot;invoice&quot; does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation &quot;invoice&quot; does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more
"/>
         <system-out><![CDATA[2019-06-13 14:42:35 - [TEST_CASE][ERROR] - Test Cases/Lemoney/DataBase/DatabaseConnection: Test Cases/Lemoney/DataBase/DatabaseConnection FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more


2019-06-13 14:42:35 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseId()): null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseVariables()): null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - println(" This is before test"): null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - url = "apiserver.cw1p29kfimzt.ap-south-1.rds.amazonaws.com": null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - dbname = "apiserver": null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - port = "5432": null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - userName = "apiserver": null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - passWord = "api-server-db-pwd": null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - queryString = "select id,bill_to,invoice_sent_at,payment_due_date,total_cost from invoice where invoice_nbr='INV_NBR_2'": null

2019-06-13 14:42:35 - [TEST_STEP][PASSED] - com.database.DemoSQLPro.connectDB(url, dbname, port, userName, passWord): com.database.DemoSQLPro.connectDB is PASSED

2019-06-13 14:42:36 - [MESSAGE][PASSED] - com.database.DemoSQLPro.connectDB is PASSED

2019-06-13 14:42:36 - [TEST_STEP][ERROR] - com.database.DemoSQLPro.executeQuery(queryString): com.database.DemoSQLPro.executeQuery(queryString) FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more


2019-06-13 14:42:36 - [MESSAGE][ERROR] - org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15

2019-06-13 14:42:36 - [MESSAGE][ERROR] - com.database.DemoSQLPro.executeQuery(queryString) FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more


2019-06-13 14:42:36 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: null

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseId()): null

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseStatus()): null]]></system-out>
         <system-err><![CDATA[2019-06-13 14:42:35 - [TEST_CASE][ERROR] - Test Cases/Lemoney/DataBase/DatabaseConnection: Test Cases/Lemoney/DataBase/DatabaseConnection FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more]]></system-err>
      </testcase>
      <testcase name="Test Cases/Lemoney/Setup and TearDown/TearDown" classname="Test Cases/Lemoney/Setup and TearDown/TearDown" status="PASSED">
         <system-out><![CDATA[2019-06-13 14:42:36 - [TEST_CASE][PASSED] - Test Cases/Lemoney/Setup and TearDown/TearDown: Test Cases/Lemoney/Setup and TearDown/TearDown

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - Start listener action : sampleBeforeTestCase: null

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseId()): null

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseVariables()): null

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - println(" This is before test"): null

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - mouseOver(findTestObject("Lemoney/Setup/Logout/img_profileImage")): Object: 'Object Repository/Lemoney/Setup/Logout/img_profileImage' is hovered

2019-06-13 14:42:36 - [MESSAGE][PASSED] - Object: 'Object Repository/Lemoney/Setup/Logout/img_profileImage' is hovered

2019-06-13 14:42:36 - [TEST_STEP][PASSED] - click(findTestObject("Lemoney/Setup/Logout/Logout")): Object: 'Object Repository/Lemoney/Setup/Logout/Logout' is clicked on

2019-06-13 14:42:37 - [MESSAGE][PASSED] - Object: 'Object Repository/Lemoney/Setup/Logout/Logout' is clicked on

2019-06-13 14:42:37 - [TEST_STEP][PASSED] - closeBrowser(): Browser is closed

2019-06-13 14:42:37 - [MESSAGE][PASSED] - Browser is closed

2019-06-13 14:42:37 - [TEST_STEP][PASSED] - Start tear down : tearDown: Method 'tearDown' complete successfully

2019-06-13 14:42:37 - [MESSAGE][PASSED] - Method 'tearDown' complete successfully

2019-06-13 14:42:37 - [TEST_STEP][PASSED] - Start listener action : sampleAfterTestCase: null

2019-06-13 14:42:37 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseId()): null

2019-06-13 14:42:37 - [TEST_STEP][PASSED] - println(testCaseContext.getTestCaseStatus()): null]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <system-out><![CDATA[2019-06-13 14:42:26 - [TEST_SUITE][ERROR] - Invoices: Test Cases/Lemoney/DataBase/DatabaseConnection FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more]]></system-out>
      <system-err><![CDATA[2019-06-13 14:42:26 - [TEST_SUITE][ERROR] - Invoices: Test Cases/Lemoney/DataBase/DatabaseConnection FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at DatabaseConnection.run(DatabaseConnection:24)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1560417143674.run(TempTestSuite1560417143674.groovy:36)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "invoice" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at java_sql_Statement$executeQuery.call(Unknown Source)
	at com.database.DemoSQLPro.executeQuery(DemoSQLPro.groovy:65)
	at com.database.DemoSQLPro.invokeMethod(DemoSQLPro.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1560411730603.run(Script1560411730603.groovy:24)
	... 13 more]]></system-err>
   </testsuite>
</testsuites>
